### ISSUE TITLE
Research GeoPackages

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyGNAT#1]
We want to explore alternatives to ShapeFiles for the new pyGNAT!

## Goal

The goal of this task is to research the feasibility of using [GeoPackages](https://www.geopackage.org/) as the primary vector storage for pyGNAT. How easy is it to write code to create GeoPackages and add, edit, delete features?

## Background

[ShapeFiles suck](http://switchfromshapefile.org/). They require too many files on disk, and they are nuisance to work with in Python. GeoPackages are a single SQLite file that is the preferred OGC format for vector data. It's also just a SQLite database, so doing basic database operations in Python can be accomplished with core Python libraries! And because it's SQLite we get away from all the archaic aspects of ShapeFiles such as 10 character field name limits and crappy 1980s data types.

GNAT is essentially an attribute building exercise. In other words, it's about adding columns to a table in a database. Let's explorer using a more open source, scalable format.

## Tasks

1. Try and use [ogr2ogr](https://gdal.org/programs/ogr2ogr.html) command line utility to convert NHDPlus HR feature class to GeoPackage.
1. Write sample to import the following NHDPlus HR geodatabase  contents into a new GeoPackage.
   1. NHDFlowline
   1. NHDPlusCatchment
   1. NHDPlusFlowlineVAA
1. Demonstrate how to add attributes and anscilliary lookup tables to the GeoPackage.

## Questions

1. How easy is it to add a GeoPackage layer to ArcMap?
1. How easy is it to add a GeoPackage layer to QGIS?
1. How does one store multiple feature classes in a single GeoPackage?

**Comment by joewheaton** [comment]
This is interesting. Just pointing ☝️ out, I am only supportive of this if answer to q1 is easy. We need to make sure we do not alienate Arc users even if we ourselves are trying not to be such users. For at least the next five years, they will be our biggest user base. Like it or not.

**Comment by philipbaileynar** [comment]
Another strategy here... I just had a polygon layer in a QGIS map and chose to export the layer. I used GeoPackage as the format. This was a really quick and easy way to generate a GeoPackage. I learned a few things quickly:

1. I was able to open the GeoPackage in my favourite SQLite software called SQLite Studio.
1. But when I tried to run some SQL, the triggers on the polygon layer table in the GeoPackage included several PostGIS geospatial functions that were not available in my SQLite Studio software. Therefore I was not able to update any records because the triggers kept failing.
1. QGIS comes with a decent "DBManager" tool that was also useful but ran into some problems.

**Comment by philipbaileynar** [comment]
Closing this issue for now. Kelly did some fine research. Lessons learned:

1. GeoPackages are easy to create in Python using OGR (here's my [demo](https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/nhd_to_geopackage.py)).
1. GeoPackage layers are easy to add to ArcMap. No extensions needed. Can be added from AddData button or ArcCatalog. Both methods present the user with a list of layers within the GeoPackage that can then be multi-selected to add to the current map.
1. GeoPackages can be read by SQLite software (both GUIs and native Python).
1. Editing GeoPackages is not possible in ArcGIS or directly using SQLite. This appears to be because GeoPackage tables have several triggers that use OGC functions to validate data. These functions are not available when connecting to the GeoPackage using non-OGC software (e.g. ArcGIS or pure SQLite). Therefore editing GeoPackage layer geometries and attributes appears only possible from OGC compliant software (QGIS and OGR etc).
1. There is an empty template GeoPackage that you can download from OGC as a file. You can also just create one within Python using OGR.
